from __future__ import annotations

CLASS_LABELS = {
    0: "Speed limit (20km/h)",
    1: "Speed limit (30km/h)",
    2: "Speed limit (50km/h)",
    3: "Speed limit (60km/h)",
    4: "Speed limit (70km/h)",
    5: "Speed limit (80km/h)",
    6: "End of speed limit (80km/h)",
    7: "Speed limit (100km/h)",
    8: "Speed limit (120km/h)",
    9: "No passing",
    10: "No passing for vehicles over 3.5 tons",
    11: "Right-of-way at the next intersection",
    12: "Priority road",
    13: "Yield",
    14: "Stop",
    15: "No vehicles",
    16: "Vehicles over 3.5 tons prohibited",
    17: "No entry",
    18: "General caution",
    19: "Dangerous curve to the left",
    20: "Dangerous curve to the right",
    21: "Double curve",
    22: "Bumpy road",
    23: "Slippery road",
    24: "Road narrows on the right",
    25: "Road work",
    26: "Traffic signals",
    27: "Pedestrians",
    28: "Children crossing",
    29: "Bicycles crossing",
    30: "Beware of ice or snow",
    31: "Wild animals crossing",
    32: "End of all speed and passing limits",
    33: "Turn right ahead",
    34: "Turn left ahead",
    35: "Ahead only",
    36: "Go straight or right",
    37: "Go straight or left",
    38: "Keep right",
    39: "Keep left",
    40: "Roundabout mandatory",
    41: "End of no passing",
    42: "End of no passing for vehicles over 3.5 tons",
}


CLASS_SHAPES = {
    0: "circle",
    1: "circle",
    2: "circle",
    3: "circle",
    4: "circle",
    5: "circle",
    6: "circle",
    7: "circle",
    8: "circle",
    9: "circle",
    10: "circle",
    11: "triangle",
    12: "diamond",
    13: "triangle_inverted",
    14: "octagon",
    15: "circle",
    16: "circle",
    17: "circle",
    18: "triangle",
    19: "triangle",
    20: "triangle",
    21: "triangle",
    22: "triangle",
    23: "triangle",
    24: "triangle",
    25: "triangle",
    26: "triangle",
    27: "triangle",
    28: "triangle",
    29: "triangle",
    30: "triangle",
    31: "triangle",
    32: "circle",
    33: "circle",
    34: "circle",
    35: "circle",
    36: "circle",
    37: "circle",
    38: "circle",
    39: "circle",
    40: "circle",
    41: "circle",
    42: "circle",
}


def label_for_class(class_id: int) -> str:
    return CLASS_LABELS.get(class_id, f"class_{class_id}")


def shape_for_class(class_id: int) -> str:
    return CLASS_SHAPES.get(class_id, "box")
